### ISSUE TITLE
bash: start_jupyter.sh: No such file or directory

### ISSUE THREAD

**Issue by snowdream** [comojin1994/DFformer#6]
When i try to run the docker image,i get errors:

```
sudo docker run --rm -it comojin1994/cu11.2-ubuntu-18.04-pytorch-1.10.0:0.8
bash: start_jupyter.sh: No such file or directory
```

where is  start_jupyter.sh?

**Comment by comojin1994** [comment]
@snowdream Oh, I'm sorry for missing that file.

The file `start_jupyter.sh` is a trivial file that is not related to this work.
However, we do not update this repository because of our next work.
So, I will attach the libraries that I used.

<img width="194" alt="image" src="https://github.com/user-attachments/assets/0c871118-fb72-46c1-bf8d-1677b948061c">

Thank you for your attention to my work!

**Comment by snowdream** [comment]
thank you.
